spring.application.name: service-registry
server:
    port: 8761
eureka:
    instance:
        hostname: localhost
    client:
        register-with-eureka: false #don't connect with yourself
        fetch-registry: false